version: "3.8"

services:
  redis:
    image: redis:7
    container_name: redisConfig-jwt
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redisConfig-server --appendonly yes
    restart: always

volumes:
  redis_data:
